stages:
  - build
  - deploy


variables:
  DOCKER_DRIVER: overlay2


build_master:
  image: "docker:cli"
  stage: build
  when: manual
  only:
    - master
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker build -t klementus/$CI_PROJECT_NAME:latest .
    - docker push klementus/$CI_PROJECT_NAME:latest


build_develop:
  image: "docker:cli"
  stage: build
  when: manual
  only:
    - develop
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker build -t klementus/$CI_PROJECT_NAME:latest .
    - docker push klementus/$CI_PROJECT_NAME:latest


deploy_master:
  image: "docker:cli"
  stage: deploy
  when: manual
  only:
    - master
  script:
    - apk add --no-cache sshpass
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker login -u '$CI_REGISTRY_USER' -p '$CI_REGISTRY_PASSWORD'"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker pull klementus/$CI_PROJECT_NAME:latest"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker stop flask || true"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker rm flask || true"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker run -d -p 8080:8080 --name flask klementus/$CI_PROJECT_NAME:latest"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker rmi -f \$(docker images -f 'dangling=true' -q)"


deploy_develop:
  image: "docker:cli"
  stage: deploy
  when: manual
  only:
    - develop
  script:
    - apk add --no-cache sshpass
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker login -u '$CI_REGISTRY_USER' -p '$CI_REGISTRY_PASSWORD'"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker pull klementus/$CI_PROJECT_NAME:latest"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker stop flask || true"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker rm flask || true"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker run -d -p 8080:8080 --name flask klementus/$CI_PROJECT_NAME:latest"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker rmi -f \$(docker images -f 'dangling=true' -q)"
